# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAjEg0dOuwy1jUguffFmIZ0cFv8TGxHv
"""

from google.colab import files
uploaded=files.upload()

# Get thinkdsp.py

import os

if not os.path.exists('thinkdsp.py'):
    !wget https://github.com/AllenDowney/ThinkDSP/raw/master/code/thinkdsp.py

from thinkdsp import read_wave

wave = read_wave('/content/file_example_WAV_1MG.wav')
wave.normalize()
wave.make_audio()

wave.plot()

segment = wave.segment(start=1, duration=5)
segment.make_audio()

segment.plot()

segment.segment(start=1.1, duration=0.005).plot()

spectrum = segment.make_spectrum()
spectrum.plot(high=1000)

spectrum.low_pass(2000)

spectrum.make_wave().make_audio()

spectrum.high_pass(50)

spectrum.make_wave().make_audio()